global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'discovery-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['discovery-service:8761']

  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway-service:8080']

  - job_name: 'ml-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ml-service:8081']

  - job_name: 'geospatial-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['geospatial-service:8082']

  - job_name: 'hydromet-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['hydromet-service:8083']