spring.application.name=gateway-service
server.port=8080

eureka.client.service-url.defaultZone=${EUREKA_SERVER:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}